### ISSUE TITLE
PRACTICA 2 VISUAL STUDIO UI - TRABAJO EN EQUIPO

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-4as_coders#1]
REPORTE DE LA PRACTICA NUMERO 2.

[PRACTICA 2 VISUAL STUDIO UI - TRABAJO EN EQUIPO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-4as_coders/files/14305988/PRACTICA.2.VISUAL.STUDIO.UI.-.TRABAJO.EN.EQUIPO.pdf)

**Comment by 22620229Angel** [comment]
nuestro equipo le da una calificacion de 95 que es igual a 19/20 ya que a nuestro parecer lleva todo los elementos de la rubrica la unica observacion es que le faltaron algunas imagenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
